apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: embedding-server
  annotations:
    scenarios.ai.sap.com/description: "Embedding API Server"
    scenarios.ai.sap.com/name: "embedding-server"
    executables.ai.sap.com/description: "REST API for text embeddings"
    executables.ai.sap.com/name: "embedding-api"
  labels:
    scenarios.ai.sap.com/id: "embedding-server"
    ai.sap.com/version: "1.0.0"
spec:
  inputs:
    parameters:
      - name: resourcePlan
        type: string
        default: "infer.s"
  template:
    apiVersion: serving.kserve.io/v1beta1
    metadata:
      annotations:
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "1"
      labels:
        ai.sap.com/resourcePlan: "{{inputs.parameters.resourcePlan}}"
    spec:
      predictor:
        minReplicas: 1
        maxReplicas: 1
        containers:
          - name: kserve-container
            image: docker.io/lokeshr11/embedding-server:latest
            ports:
              - containerPort: 8080
                protocol: TCP
            resources:
              requests:
                memory: 4Gi
                cpu: "2"
              limits:
                memory: 8Gi
                cpu: "4"
